=== budde377/Part/xsd/site-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://christianbud.de/site-config"
           xmlns="http://christianbud.de/site-config"
           elementFormDefault="qualified">

    <xs:element name="config">
        <xs:complexType>
            <xs:all>
                <xs:element name="siteInfo" minOccurs="1" >
                    <xs:complexType>
                        <xs:all minOccurs="1">
                            <xs:element name="domain">
                                <xs:complexType>
                                    <xs:attribute name="name" type="xs:string" use="required"/>
                                    <xs:attribute name="extension" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="owner">
                                <xs:complexType>
                                    <xs:attribute name="name" use="required" type="xs:string"/>
                                    <xs:attribute name="mail" use="required" type="xs:string"/>
                                    <xs:attribute name="username" use="required" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="defaultPages" type="pageSequence" minOccurs="0">
                    <xs:unique name="pageTitle">
                        <xs:selector xpath="page"/>
                        <xs:field xpath="@title"/>
                    </xs:unique>
                </xs:element>
                <xs:element name="preScripts" type="linkedValClassSequence" minOccurs="0">
                    <xs:unique name="preScriptName">
                        <xs:selector xpath="class"/>
                        <xs:field xpath="."/>
                    </xs:unique>
                </xs:element>

                <xs:element name="AJAXTypeHandlers" type="linkedValClassSequence" minOccurs="0">
                    <xs:unique name="AJAXTypeHandlersName">
                        <xs:selector xpath="class"/>
                        <xs:field xpath="."/>
                    </xs:unique>
                </xs:element>
                <xs:element name="postScripts" type="linkedValClassSequence" minOccurs="0">
                    <xs:unique name="postScriptName">
                        <xs:selector xpath="class"/>
                        <xs:field xpath="."/>
                    </xs:unique>
                </xs:element>
                <xs:element name="templates" type="templateSequence" minOccurs="0"/>
                <xs:element name="pageElements" type="namedLinkedValClassSequence" minOccurs="0">
                    <xs:unique name="pageElementName">
                        <xs:selector xpath="class"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
                <xs:element name="MySQLConnection" type="dbConnectionWithPassword" minOccurs="0"/>
                <xs:element name="MailMySQLConnection" type="dbConnection" minOccurs="0"/>
                <xs:element name="debugMode" type="xs:boolean" minOccurs="0"/>
                <xs:element name="enableUpdater" type="xs:boolean" minOccurs="0" />
                <xs:element name="optimizers" type="namedLinkedValClassSequence" minOccurs="0">
                    <xs:unique name="optimizerName">
                        <xs:selector xpath="class"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
                <xs:element name="tmpFolder" type="requiredPathAttribute" minOccurs="0"/>
                <xs:element name="log" type="requiredPathAttribute" minOccurs="0" />
                <xs:element name="facebookApp" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="secret" type="xs:string" use="required"/>
                        <xs:attribute name="permanent_token" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>



    <xs:complexType name="dbConnection">
        <xs:all>
            <xs:element name="host" type="xs:anyURI"/>
            <xs:element name="database" type="xs:string"/>
            <xs:element name="username" type="xs:string"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="dbConnectionWithPassword">
        <xs:all>
            <xs:element name="host" type="xs:anyURI"/>
            <xs:element name="database" type="xs:string"/>
            <xs:element name="username" type="xs:string"/>
            <xs:element name="password" type="xs:string" />

        </xs:all>
    </xs:complexType>

    <xs:complexType name="pageSequence">
        <xs:sequence>
            <xs:element name="page" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="alias" type="xs:string" use="required"/>
                            <xs:attribute name="template" type="xs:string" use="required"/>
                            <xs:attribute name="id" type="name" use="required" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="templateSequence">
        <xs:complexContent>
            <xs:extension base="requiredPathAttribute">
                <xs:sequence>
                    <xs:element name="template" maxOccurs="unbounded" minOccurs="0">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="xs:string">
                                    <xs:attribute name="filename" type="xs:string" />
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="requiredPathAttribute">
        <xs:attribute name="path" type="xs:anyURI" use="required"/>
    </xs:complexType>

    <xs:complexType name="linkedValClassSequence">
        <xs:sequence>
            <xs:element name="class" type="linkedVal" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="ajaxIdLinkedValClassSequence">
        <xs:sequence>
            <xs:element name="class" type="ajaxIdLinkedVal" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="namedLinkedValClassSequence">
        <xs:sequence>
            <xs:element name="class" type="namedLinkedVal" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="linkedVal">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:anyURI" name="link" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:complexType name="namedLinkedVal">
        <xs:simpleContent>
            <xs:extension base="linkedVal">
                <xs:attribute type="name" name="name" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="ajaxIdLinkedVal">
        <xs:simpleContent>
            <xs:extension base="linkedVal">
                <xs:attribute type="name" name="ajax_id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-zA-Z\-_]+"/>
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== budde377/Part/site-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns="http://christianbud.de/site-config"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:schemaLocation="http://christianbud.de/site-config site-config.xsd">
    <templates>
        <template link="_template/MainTemplate.xhtml">_404</template>
    </templates>
    <pageElements>
        <class name="title" link="_local_class/TitlePageElementImpl.php">TitlePageElementImpl</class>
    </pageElements>
    <MySQLConnection>
        <host>192.168.1.1</host>
        <database>cms2012</database>
        <username>cms2012</username>
        <password>plovMand50</password>
    </MySQLConnection>
    <optimizers>
        <class name="css" link="_class/CSSYUICompressorOptimizerImpl.php">CSSYUICompressorOptimizerImpl</class>
        <class name="js" link="_class/JSYUICompressorOptimizerImpl.php">JSYUICompressorOptimizerImpl</class>
    </optimizers>
</config>
